stages:
  prepare:
    cmd: python src/prepare.py data/data.xml
    deps:
    - data/data.xml
    - src/prepare.py
    params:
    - prepare.seed
    - prepare.split
    outs:
    - data/prepared
  featurize:
    cmd: python src/featurization.py data/prepared data/features
    params:
    - featurize.max_features
    - featurize.ngrams
    deps:
    - data/prepared
    - src/featurization.py
    outs:
    - data/features
  train:
    cmd: python src/train.py data/features model.pkl
    params:
    - train.min_split
    - train.n_est
    - train.seed
    deps:
    - data/features
    - src/train.py
    outs:
    - model.pkl
